packages:
  - 'packages/*'
  - 'tools/*'
  - "mcp"
  - "cli"

catalog:
  # Build tools
  tsup: ^8.0.1
  typescript: ^5.3.3

  # Testing
  vitest: ^1.2.0
  '@vitest/ui': ^1.2.0

  # Linting & Formatting
  eslint: ^8.56.0
  prettier: ^3.2.4

  # Type checking
  '@types/node': ^20.11.0
  '@types/react': ^19.1.9
  '@types/react-dom': ^19.1.9

  # React ecosystem - SHARED VERSIONS (React 19.1.0 for all)
  react: 19.1.0
  react-dom: 19.1.0

  # Common dependencies
  zod: ^3.25.76
  clsx: ^2.1.1
  tailwind-merge: ^3.3.1
  dayjs: ^1.11.13
  '@hookform/resolvers': ^5.2.1
  'react-hook-form': ^7.62.0
  '@tanstack/react-query': ^5.84.1

pnpm:
  overrides:
    zod: ^3.22.4
    # React 19.1.0 for all packages (Expo SDK 54 requirement)
    react: 19.1.0
    react-dom: 19.1.0
    "@types/react": ^19.1.9
    "@types/react-dom": ^19.1.9
  peerDependencyRules:
    allowedVersions:
      # Allow React 19 for older libraries that don't officially support it yet
      "@react-aria/checkbox>react": "19"
      "next>react": "19"
      "next>react-dom": "19"
      "lucide-react>react": "19"
      "@expo/webpack-config>expo": "54"
    ignoreMissing:
      - "@types/inquirer"