packages:
  - 'packages/*'
  - 'tools/*'
  - "mcp"

catalog:
  # Build tools
  tsup: ^8.0.1
  typescript: ^5.3.3
  
  # Testing
  vitest: ^1.2.0
  '@vitest/ui': ^1.2.0
  
  # Linting & Formatting
  eslint: ^8.56.0
  prettier: ^3.2.4
  
  # Type checking
  '@types/node': ^20.11.0
  # Common dependencies
  zod: ^3.25.0

pnpm:
  overrides:
    zod: ^3.22.4