version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: packages/api/Dockerfile
      args:
        DOPPLER_PROJECT: gymspace
        DOPPLER_ENV: dev
    container_name: gymspace-api-dev
    restart: unless-stopped
    ports:
      - '5200:5200'
    environment:
      # Doppler service token for development
      DOPPLER_SERVICE_TOKEN: ${DOPPLER_SERVICE_TOKEN}
      # Override NODE_ENV for development
      NODE_ENV: development
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5200/api/v1/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - default

networks:
  default:
    name: gymspace-network
