version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: packages/api/Dockerfile
    container_name: gymspace-api-local
    restart: unless-stopped
    ports:
      - '5200:5200'
    env_file:
      - ../packages/api/.env
    environment:
      # Override Redis configuration to connect to the Redis container
      REDIS_HOST: gymspace-redis
      REDIS_PORT: 6379
      NODE_ENV: development
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5200/api/v1/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - default

networks:
  default:
    name: gymspace-network
