#!/bin/bash
set -e

echo "🔍 Starting Android build with explicit environment..."
echo "ANDROID_HOME: /Users/leobar37/Library/Android/sdk"
echo "Current directory: $(pwd)"
echo "==================================="

# Set explicit environment variables
export ANDROID_HOME="/Users/leobar37/Library/Android/sdk"
export ANDROID_SDK_ROOT="/Users/leobar37/Library/Android/sdk"
export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH"

# Verify environment
echo "✅ Verifying SDK access..."
ls "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" >/dev/null 2>&1 && echo "✅ sdkmanager found" || { echo "❌ sdkmanager not found"; exit 1; }

# Create/verify local.properties
echo "✅ Creating local.properties..."
cat > android/local.properties << EOF
# This file was automatically generated by the system.
# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
# This file must NOT be checked into Version Control Systems,
# as it contains information specific to your local configuration.

# Location of the SDK. This is only used by Gradle.
# For customization when using a Version Control System, please read the
# header note.
sdk.dir=/Users/leobar37/Library/Android/sdk
EOF

echo "✅ local.properties created:"
cat android/local.properties
echo ""

# Run the actual build
echo "🚀 Starting EAS build with explicit environment..."
EAS_LOCAL_BUILD_SKIP_CLEANUP=1 eas build --platform android --local --verbose

echo "✅ Build complete!"